

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE TABLE IF NOT EXISTS `categories` (
  `id_categorie` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `categorie_principale` varchar(50) DEFAULT NULL,
  `sous_categorie` varchar(50) DEFAULT NULL,
  `sous_categorie2` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id_categorie`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO `categories` (`id_categorie`, `categorie_principale`, `sous_categorie`, `sous_categorie2`) VALUES
(1, 'Cuisine', 'Cuisine française', 'Bistrots, brasseries et bars à vin'),
(2, 'Cuisine', 'Cuisine française', 'Crêperies'),
(3, 'Cuisine', 'Cuisine française', 'Cuisine des régions'),
(4, 'Cuisine', 'Cuisine française', 'Cuisine du marché'),
(5, 'Cuisine', 'Cuisine française', 'Cuisine fusion'),
(6, 'Cuisine', 'Cuisine française', 'Cuisine traditionnelle'),
(7, 'Cuisine', 'Cuisine française', 'Gastronomique'),
(8, 'Cuisine', 'Cuisine du monde', 'Africaine'),
(9, 'Cuisine', 'Cuisine du monde', 'Asiatique'),
(10, 'Cuisine', 'Cuisine du monde', 'Créole et tahitienne'),
(11, 'Cuisine', 'Cuisine du monde', 'Latino-américaine'),
(12, 'Cuisine', 'Cuisine du monde', 'Nord-américaine'),
(13, 'Cuisine', 'Cuisine du monde', 'Méridionale'),
(14, 'Cuisine', 'Cuisine du monde', 'Orientale'),
(15, 'Cuisine', 'Cuisine du monde', 'Slave'),
(16, 'Cuisine', 'Cuisine du monde', 'Scandinave'),
(17, 'Cuisine', 'Glaciers et salons de thé', 'Bars à fruit'),
(18, 'Cuisine', 'Glaciers et salons de thé', 'Glaciers'),
(19, 'Cuisine', 'Glaciers et salons de thé', 'Salons de thé'),
(20, 'Cuisine', 'Sandwicheries, cafétérias et restauration rapide', NULL),
(21, 'Cuisine', 'Autres restauration', NULL),
(22, 'Cuisine', 'Alimentation générale', NULL),
(23, 'Cuisine', 'Boucheries et charcuteries', 'Boucherie halal'),
(24, 'Cuisine', 'Boucheries et charcuteries', 'Boucherie casher'),
(25, 'Cuisine', 'Boucheries et charcuteries', 'Boucherie traditionnelle'),
(26, 'Cuisine', 'Boulangeries et pâtisseries', NULL),
(27, 'Cuisine', 'Cavistes', NULL),
(28, 'Cuisine', 'Chocolatiers et confiseurs', NULL),
(29, 'Cuisine', 'Crèmeries et fromageries', NULL),
(30, 'Cuisine', 'Diététique et alimentation bio', NULL),
(31, 'Cuisine', 'Epiceries fines', NULL),
(32, 'Cuisine', 'Poissonneries', NULL),
(33, 'Cuisine', 'Primeurs', NULL),
(34, 'Cuisine', 'Surgelés', NULL),
(35, 'Cuisine', 'Torréfacteurs et maisons de thé', NULL),
(36, 'Cuisine', 'Traiteurs', NULL),
(37, 'Cuisine', 'Autres alimentation', NULL),
(38, 'Beauté et bien être', 'Centres de bronzage et solariums', NULL),
(39, 'Beauté et bien être', 'Instituts de beauté et spas', NULL),
(40, 'Beauté et bien être', 'Hammams et saunas', NULL),
(41, 'Beauté et bien être', 'Magasins spécialisés', 'Cosmétiques'),
(42, 'Beauté et bien être', 'Magasins spécialisés', 'Soin du cheveu'),
(43, 'Beauté et bien être', 'Parfumeries', NULL),
(44, 'Beauté et bien être', 'Salons de coiffure', 'Enfants'),
(45, 'Beauté et bien être', 'Salons de coiffure', 'Femmes'),
(46, 'Beauté et bien être', 'Salons de coiffure', 'Hommes'),
(47, 'Beauté et bien être', 'Salons de coiffure', 'Mixte'),
(48, 'Beauté et bien être', 'Salons de massage', NULL),
(49, 'Beauté et bien être', 'Autres beaute et bien etre', NULL),
(50, 'Culture', 'Arts graphiques', 'Cours et ateliers'),
(51, 'Culture', 'Arts graphiques', 'Evénements et festivals'),
(52, 'Culture', 'Arts graphiques', 'Magasins spécialisés'),
(53, 'Culture', 'Arts graphiques', 'Papeteries et carteries'),
(54, 'Culture', 'Beaux-arts', 'Cours et écoles d''art'),
(55, 'Culture', 'Beaux-arts', 'Galeries d''art'),
(56, 'Culture', 'Beaux-arts', 'Musées et expositions'),
(57, 'Culture', 'Cinéma et vidéo', 'Cinémas'),
(58, 'Culture', 'Cinéma et vidéo', 'Evénements et festivals'),
(59, 'Culture', 'Cinéma et vidéo', 'Vidéoclubs'),
(60, 'Culture', 'Littératures', 'Bibliothèques'),
(61, 'Culture', 'Littératures', 'Evénements et festivals'),
(62, 'Culture', 'Littératures', 'Librairies et bouquinistes'),
(63, 'Culture', 'Musique', 'Cours et écoles de musique'),
(64, 'Culture', 'Musique', 'Disquaires'),
(65, 'Culture', 'Musique', 'Evénements et festivals'),
(66, 'Culture', 'Musique', 'Librairies musicales'),
(67, 'Culture', 'Musique', 'Luthiers et magasins d''instruments'),
(68, 'Culture', 'Musique', 'Salles de concert'),
(69, 'Culture', 'Photographie', 'Cours et ateliers'),
(70, 'Culture', 'Photographie', 'Galeries et expositions'),
(71, 'Culture', 'Photographie', 'Studios photo et magasins spécialisés'),
(72, 'Culture', 'Théâtre, opéra et spectacle vivant', 'Cours et ateliers'),
(73, 'Culture', 'Théâtre, opéra et spectacle vivant', 'Cirques'),
(74, 'Culture', 'Théâtre, opéra et spectacle vivant', 'Evénements et festivals'),
(75, 'Culture', 'Théâtre, opéra et spectacle vivant', 'Opéras'),
(76, 'Culture', 'Théâtre, opéra et spectacle vivant', 'Théâtres'),
(77, 'Culture', 'Général', 'Centres culturels'),
(78, 'Culture', 'Général', 'Grandes surfaces spécialisées'),
(79, 'Mode et design', 'Ameublement', 'Antiquaires'),
(80, 'Mode et design', 'Ameublement', 'Cuisinistes'),
(81, 'Mode et design', 'Ameublement', 'Grandes surfaces spéclalisées'),
(82, 'Mode et design', 'Ameublement', 'Magasins spécialisés'),
(83, 'Mode et design', 'Décoration', 'Brocantes'),
(84, 'Mode et design', 'Décoration', 'Encadrement'),
(85, 'Mode et design', 'Décoration', 'Fleuristes'),
(86, 'Mode et design', 'Décoration', 'Luminaires'),
(87, 'Mode et design', 'Décoration', 'Linge et textiles de maison'),
(88, 'Mode et design', 'Décoration', 'Magasins spécialisés'),
(89, 'Mode et design', 'Electroménager et matériel informatique', 'Grandes surfaces'),
(90, 'Mode et design', 'Electroménager et matériel informatique', 'Magasins spécialisés'),
(91, 'Mode et design', 'Autres équipement et articles de maison', 'Articles de cuisine'),
(92, 'Mode et design', 'Autres équipement et articles de maison', 'Autres magasins spécialisés'),
(93, 'Mode et design', 'Jardineries', NULL),
(94, 'Mode et design', 'Bijouteries', 'Fantaisie'),
(95, 'Mode et design', 'Bijouteries', 'Luxe'),
(96, 'Mode et design', 'Chausseurs', 'Enfants'),
(97, 'Mode et design', 'Chausseurs', 'Femmes'),
(98, 'Mode et design', 'Chausseurs', 'Hommes'),
(99, 'Mode et design', 'Chausseurs', 'Mixte'),
(100, 'Mode et design', 'Chausseurs', 'Spécialisés'),
(101, 'Mode et design', 'Magasins de prêt-à-porter', 'Enfants'),
(102, 'Mode et design', 'Magasins de prêt-à-porter', 'Femmes'),
(103, 'Mode et design', 'Magasins de prêt-à-porter', 'Futures mamans'),
(104, 'Mode et design', 'Magasins de prêt-à-porter', 'Hommes'),
(105, 'Mode et design', 'Magasins de prêt-à-porter', 'Mixte'),
(106, 'Mode et design', 'Magasins de prêt-à-porter', 'Spécialisés'),
(107, 'Mode et design', 'Haute-Couture', 'Femmes'),
(108, 'Mode et design', 'Haute-Couture', 'Hommes'),
(109, 'Mode et design', 'Haute-Couture', 'Mariage'),
(110, 'Mode et design', 'Haute-Couture', 'Mixte'),
(111, 'Mode et design', 'Friperies', NULL),
(112, 'Mode et design', 'Solderies', NULL),
(113, 'Mode et design', 'Ganteries', NULL),
(114, 'Mode et design', 'Chapelleries', NULL),
(115, 'Mode et design', 'Maroquineries', NULL),
(116, 'Mode et design', 'Divers / accessoires', 'Colifichets et foulards'),
(117, 'Mode et design', 'Divers / accessoires', 'Montres'),
(118, 'Mode et design', 'Divers / accessoires', 'Parapluies'),
(119, 'Mode et design', 'Divers / accessoires', 'Perruques'),
(120, 'Santé', 'Centres de thalasso', NULL),
(121, 'Santé', 'Equipement médical', NULL),
(122, 'Santé', 'Laboratoire médical', NULL),
(123, 'Santé', 'Maisons médicales', NULL),
(124, 'Santé', 'Opticiens et acoustique', NULL),
(125, 'Santé', 'Pharmacies et parapharmacies', NULL),
(126, 'Santé', 'Soins vétérinaires', NULL),
(127, 'Sorties, voyages et loisirs', 'Bars', 'Bars à cocktails'),
(128, 'Sorties, voyages et loisirs', 'Bars', 'Bars à thèmes'),
(129, 'Sorties, voyages et loisirs', 'Bars', 'Bars à vins'),
(130, 'Sorties, voyages et loisirs', 'Bars', 'Bars de jazz'),
(131, 'Sorties, voyages et loisirs', 'Bars', 'Bars karaoké'),
(132, 'Sorties, voyages et loisirs', 'Bars', 'Bars lounge'),
(133, 'Sorties, voyages et loisirs', 'Cabarets', NULL),
(134, 'Sorties, voyages et loisirs', 'Pubs', NULL),
(135, 'Sorties, voyages et loisirs', 'Night clubs', 'Généraliste'),
(136, 'Sorties, voyages et loisirs', 'Night clubs', 'Hip Hop, Rap, R''n''B'),
(137, 'Sorties, voyages et loisirs', 'Night clubs', 'House'),
(138, 'Sorties, voyages et loisirs', 'Night clubs', 'Techno Electro'),
(139, 'Sorties, voyages et loisirs', 'Night clubs', 'Musiques latines'),
(140, 'Sorties, voyages et loisirs', 'Night clubs', 'Autres'),
(141, 'Sorties, voyages et loisirs', 'Billards', NULL),
(142, 'Sorties, voyages et loisirs', 'Bowlings', NULL),
(143, 'Sorties, voyages et loisirs', 'Déguisements, farces et attrapes', NULL),
(144, 'Sorties, voyages et loisirs', 'Jeux', 'Magasins de jouets'),
(145, 'Sorties, voyages et loisirs', 'Jeux', 'Magasins de jeux enfants et adultes'),
(146, 'Sorties, voyages et loisirs', 'Jeux', 'Salles de jeu'),
(147, 'Sorties, voyages et loisirs', 'Modélisme', NULL),
(148, 'Sorties, voyages et loisirs', 'Parcs d''attraction', NULL),
(149, 'Sorties, voyages et loisirs', 'Parcs et nature', NULL),
(150, 'Sorties, voyages et loisirs', 'Voyages', 'Agences de voyage'),
(151, 'Sorties, voyages et loisirs', 'Voyages', 'Compagnies de transport'),
(152, 'Sorties, voyages et loisirs', 'Voyages', 'Hébergement'),
(153, 'Sorties, voyages et loisirs', 'Autres sorties, voyages et loisirs', NULL),
(154, 'Services et inclassables', 'Achat d''or', NULL),
(155, 'Services et inclassables', 'Agences immobilières', NULL),
(156, 'Services et inclassables', 'Agences intérimaires', NULL),
(157, 'Services et inclassables', 'Assureurs', NULL),
(158, 'Services et inclassables', 'Banques', NULL),
(159, 'Services et inclassables', 'Bureaux de tabac', NULL),
(160, 'Services et inclassables', 'Cordonneries', NULL),
(161, 'Services et inclassables', 'Concessionnaires', NULL),
(162, 'Services et inclassables', 'Electriciens', NULL),
(163, 'Services et inclassables', 'Grande distribution', 'Hypermarchés'),
(164, 'Services et inclassables', 'Grande distribution', 'Supermarchés'),
(165, 'Services et inclassables', 'Grande distribution', 'Supérettes'),
(166, 'Services et inclassables', 'Grande distribution', 'Discount'),
(167, 'Services et inclassables', 'Laveries', NULL),
(168, 'Services et inclassables', 'Location de véhicules', NULL),
(169, 'Services et inclassables', 'Maisons de la presse', NULL),
(170, 'Services et inclassables', 'Ménage à domicile', NULL),
(171, 'Services et inclassables', 'Plombiers', NULL),
(172, 'Services et inclassables', 'Pressings et nettoyage à sec', NULL),
(173, 'Services et inclassables', 'Réparation TV-Hifi-informatique', NULL),
(174, 'Services et inclassables', 'Serruriers', NULL),
(175, 'Services et inclassables', 'Stations-services', NULL),
(176, 'Erotique', 'Sexshop', NULL),
(177, 'Erotique', 'Clubs privés', NULL);